webapp:js:
  - changed-files:
      - any-glob-to-any-file: ['**/*.tsx', '**/*.ts']

webapp:css:
  - changed-files:
      - any-glob-to-any-file: ['**/*.scss', '**/*.css']

env_changed:
  - changed-files:
      - any-glob-to-any-file: ['**/*.env*']
