name: Build WebOS App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build"
        required: false
        default: "Development"
        type: choice
        options:
          - Development
          - Production

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Production' || 'Development') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install webOS CLI
        run: |
          npm install -g @webos-tools/cli

      - name: Set Environment URL
        run: echo "URL=${{ vars.WEBSITE_URL }}" >> $GITHUB_ENV

      - name: Replace URL in template and build
        run: |
          cd platforms/lg
          envsubst < index.html.tpl > index.html
          ares-package .

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: feralfile-webos-app
          path: platforms/lg/*.ipk
