name: Build

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'next.config.mjs'
      - 'public/**'
      - 'eslint.config.mjs'
      - 'sentry*.ts'
      - '.env.local.sample'
      - '.github/workflows/build-website.yaml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'next.config.mjs'
      - 'public/**'
      - 'eslint.config.mjs'
      - 'sentry*.ts'
      - '.env.local.sample'
      - '.github/workflows/build-website.yaml'

permissions:
  contents: read
  issues: write

concurrency:
  group: build-website-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        environment: [Development, Production]
    name: Build ${{ matrix.environment }}
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables for ${{ matrix.environment }}
        run: |
          echo "NEXT_PUBLIC_ENVIRONMENT=${{ vars.ENVIRONMENT }}" >> .env.local
          echo "NEXT_PUBLIC_PUB_DOC_URL=${{ vars.PUB_DOC_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SENTRY_DSN=${{ vars.SENTRY_DSN }}" >> .env.local

      - name: Check for missing environment variables
        id: check_env_vars
        run: |
          missing=false
          warnings=()

          # Check each key in .env.local.sample to see if it has a value in .env.local
          while IFS= read -r line; do
            key=$(echo $line | cut -d '=' -f 1)

            # Extract the value of the corresponding key from .env.local
            value=$(grep -m 1 "^$key=" .env.local | cut -d '=' -f 2-)

            # If the key is missing or has an empty value, log a warning
            if [ -z "$value" ]; then
              warnings+=("\"$key is missing or has an empty value in .env.local\"")
              missing=true
            fi
          done < .env.local.sample

          # Handle setting the output and state only if there are warnings
          if [ "$missing" = true ]; then
            warnings_json=$(printf "%s\n" "${warnings[@]}" | jq -R . | jq -s .)
            echo "warnings=$warnings_json" >> $GITHUB_OUTPUT
          else
            echo "warnings=[]" >> $GITHUB_OUTPUT
          fi

      - name: Add GitHub comment with warnings if any
        if: github.event_name == 'pull_request' && steps.check_env_vars.outputs.warnings != '[]'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const warningsOutput = '${{ steps.check_env_vars.outputs.warnings }}';
            if (warningsOutput && warningsOutput !== '[]') {
              const warnings = JSON.parse(warningsOutput);
              const body = warnings.map(warning => `- ${warning}`).join('\n');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## :warning: Environment Variables and Secrets Warnings:\n${body}`
              });
            }

      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js app
        run: npm run build
