name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build'
        required: false
        default: 'Development'
        type: choice
        options:
          - Development
          - Production

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Production' || 'Development') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_INDEXER_MAINNET_URL=${{ vars.INDEXER_MAINNET_URL }}" >> .env.local
          echo "NEXT_PUBLIC_ACCOUNTS_URL=${{ vars.ACCOUNTS_URL }}" >> .env.local
          echo "NEXT_PUBLIC_AUTONOMY_IPFS_PREFIX=${{ vars.AUTONOMY_IPFS_PREFIX }}" >> .env.local
          echo "NEXT_PUBLIC_FERAL_FILE_ASSET_URL=${{ vars.FERAL_FILE_ASSET_URL }}" >> .env.local
          echo "NEXT_PUBLIC_API_URL=${{ vars.API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_PUB_DOC_URL=${{ vars.PUB_DOC_URL }}" >> .env.local
          echo "NEXT_PUBLIC_WEBSOCKET_URL=${{ vars.WEBSOCKET_URL }}" >> .env.local
          echo "NEXT_PUBLIC_ACCOUNTS_API_KEY=${{ secrets.ACCOUNTS_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_API_KEY=${{ secrets.WEBSOCKET_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_BRANCH_KEY=${{ secrets.BRANCH_KEY }}" >> .env.local

      - name: Build Next.js app
        run: npm run build

      - name: Write the current version hash
        run: |
          echo "{\"version\": \"$(git rev-parse HEAD)\"}" > out/version.json

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_ID }}
          directory: out
          wranglerVersion: '3'
