name: Deploy

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build"
        required: false
        default: "Development"
        type: choice
        options:
          - Development
          - Production

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Production' || 'Development') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Set environment variables for ${{ matrix.environment }}
        run: |
          echo "NEXT_PUBLIC_INDEXER_MAINNET_URL=${{ vars[matrix.environment].INDEXER_MAINNET_URL }}"  >> .env.local
          echo "NEXT_PUBLIC_AUTONOMY_IPFS_PREFIX=${{ vars[matrix.environment].AUTONOMY_IPFS_PREFIX }}"  >> .env.local
          echo "NEXT_PUBLIC_FERAL_FILE_ASSET_URL=${{ vars[matrix.environment].FERAL_FILE_ASSET_URL }}"  >> .env.local
          echo "NEXT_PUBLIC_API_URL=${{ vars[matrix.environment].API_URL }}"  >> .env.local
          echo "NEXT_PUBLIC_PUB_DOC_URL=${{ vars[matrix.environment].PUB_DOC_URL }}"  >> .env.local
          echo "NEXT_PUBLIC_WEBSOCKET_URL=${{ vars[matrix.environment].WEBSOCKET_URL }}"  >> .env.local
          echo "NEXT_PUBLIC_WEBSOCKET_API_KEY=${{ secrets[matrix.environment].WEBSOCKET_API_KEY }}"  >> .env.local
          echo "NEXT_PUBLIC_BRANCH_KEY=${{ secrets[matrix.environment].BRANCH_KEY }}"  >> .env.local

      - name: Build Next.js app
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_ID }}
          directory: out
          wranglerVersion: "3"
