name: Lint CSS

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.scss'
      - '**.css'

jobs:
  lint:
    name: Lint
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: TYPO check
      uses: reviewdog/action-typos@v1
      with:
        reporter: github-pr-review
    
    - name: stylelint
      uses: reviewdog/action-stylelint@v1
      with:
        reporter: github-pr-review
        stylelint_input: 'src/*.css'